version: '3.8'

services:
  app:
    image: dockerrizedappsample
    container_name: dockerrizedappsample_app
    build:
      context: .
      dockerfile: DockerizedAppSample/Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_CONNECTION_STRING=Host=db;Database=example_db;Username=postgres;Password=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: dockerrizedappsample_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5