version: '3.8'

services:
  app:
    image: ${{ secrets.DOCKER_USERNAME }}/dockerrizedappsample:latest
    container_name: dockerrizedappsample_app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: dockerrizedappsample_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432