name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: DockerizedAppSample/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/dockerrizedappsample:latest

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/dockerrizedappsample:latest

    - name: Run Docker container
      run: docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/dockerrizedappsample:latest

    - name: Set up ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ./ngrok http 8080 &

    - name: Wait for ngrok to start
      run: sleep 10

    - name: Get ngrok URL
      id: ngrok
      run: echo "::set-output name=url::$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)"

    - name: Output ngrok URL
      run: echo "Ngrok URL: ${{ steps.ngrok.outputs.url }}"
